/*
 * Copyright 2010 OpenHealthData, Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.

 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
 #created on: Apr 29, 2008
package org.astm.ccr.rules.v1

#list any import classes here.
import org.openhealthdata.validation.result.ValidationResultManager;
import org.openhealthdata.validation.result.ErrorType;
import org.openhealthdata.validation.result.TestResultType;
import org.astm.ccr.DateTimeType;


#declare any global variables here
global ValidationResultManager val_result;

/*
	The regular expression for ISO8601 is from Cameron Brooks in a comment on:
		http://underground.infovark.com/2008/07/22/iso-date-validation-regex/
	//TODO need to update to limit to W notation and it doesn’t account for 
		the duration or time interval part of the ISO 8601 spec
*/
rule "ExactDateTime must be in the format of ISO8601"
@title (ExactDateTime must be in the format of ISO8601)
@testid (104b4fe2-1bdc-81e4-7d2c-d327cb859bb6)
@description (This test makes sure that ExactDateTime formatted according to ISO 8601)
@source (E2369-05 Section A1.1)
@profile (E2369-05)
@author (openhealthdata)
	when
		$d:DateTimeType($e:exactDateTime not matches "^([\\+-]?\\d{4}(?!\\d{2}\\b))((-?)((0[1-9]|1[0-2])(\\3([12]\\d|0[1-9]|3[01]))?|W([0-4]\\d|5[0-2])(-?[1-7])?|(00[1-9]|0[1-9]\\d|[12]\\d{2}|3([0-5]\\d|6[1-6])))([T\\s]((([01]\\d|2[0-3])((:?)[0-5]\\d)?|24\\:?00)([\\.,]\\d+(?!:))?)?(\\17[0-5]\\d([\\.,]\\d+)?)?([zZ]|([\\+-])([01]\\d|2[0-3]):?([0-5]\\d)?)?)?)?$")
	then
		String testid = drools.getRule().getMetaAttribute("testid");
		String title = drools.getRule().getMetaAttribute("title");
		String description = drools.getRule().getMetaAttribute("description");
		String source = drools.getRule().getMetaAttribute("source");
		String profile = drools.getRule().getMetaAttribute("profile"); 
		val_result.addTest(
			testid,
			title,
			description+ " Source: "+
			source,
			TestResultType.FAILED, profile);
		ErrorType e = new ErrorType();
		e.setMessage("ExactDateTime ["+
			$e+"] does not conform to the right format i.e. (yyyy-mm-ddThh:mm:ss.ss[Z or +-hh:mm])");
		e.setServerity(ErrorType.FATAL);
		val_result.addError(testid, e);
end
