/*
 * Copyright 2010 OpenHealthData, Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.

 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
 #created on: Apr 29, 2008
package org.astm.ccr.rules.v1

#list any import classes here.
import org.openhealthdata.validation.result.ValidationResultManager;
import org.openhealthdata.validation.result.ErrorType;
import org.openhealthdata.validation.result.TestResultType;
import org.astm.ccr.InternalCCRLink;
import org.astm.ccr.CCRCodedDataObjectType;
import org.astm.ccr.ActorType;


#declare any global variables here
global ValidationResultManager val_result;

rule "Every InternalCCRLink must point to an ObjectID"
@title ("InternalCCRLink must point to a CCRDataObjectID")
@testid ("abd95ef3-778b-90d5-8c3b-e0ac98a960cc7")
@description ("This test makes sure that every <InternalCCRLink><linkID> contains a value equal to a <CCRCodedDataObjectType> or <ActorObjectID>.")
@source ("E2369-05 Table A1.1")
@profile ("E2369-05")
@author ("openhealthdata")
	when
		InternalCCRLink( $id:linkID )
		not CCRCodedDataObjectType( CCRDataObjectID == $id )
		not ActorType( actorObjectID == $id )
	then
		val_result
	    .addFailed( drools.getRule() )
	    .addFatal( "InternalCCRLink with linkID of [" + $id +
	               "] does not equal any ActorObjectID or CCRDataObjectID" );
end

