/*
 * Copyright 2010 OpenHealthData, Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.

 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
 #created on: Apr 29, 2008
package org.astm.ccr.rules.v1

#list any import classes here.
import org.openhealthdata.validation.result.ValidationResultManager;
import org.openhealthdata.validation.result.TestResultType;
import org.openhealthdata.validation.result.ErrorType;

import java.util.List;
import org.astm.ccr.PatientKnowledgeType;
import org.astm.ccr.InternalCCRLink;
import org.astm.ccr.SourceType;


#declare any global variables here
global ValidationResultManager val_result;

rule "Patient aware in patient knowledge must be either Yes, No, or Unknown"
@title ("Patient aware in patient knowledge must be either Yes, No, or Unknown")
@testid ("7779fbbc-2d81-4041-bf09-0074a35ab09d")
@description ("Patient aware in patient knowledge must be either Yes, No, or Unknown")
@source ("E2369-05 Table A1.1 Page 16")
@profile ("E2369-05")
@author ("openhealthdata")
	when
		PatientKnowledgeType($pa: patientAware, patientAware not in ("Yes", "No", "Unknown"))
	then
		val_result
	    .addFailed( drools.getRule() )
	    .addFatal( "The string [" + $pa + "] in <PatientAware> is not a valid value" );
end

