/*
 * Copyright 2010 OpenHealthData, Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.

 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
 #created on: Apr 29, 2008
package org.astm.ccr.rules.v1

#list any import classes here.
import org.openhealthdata.validation.result.ValidationResultManager;
import org.openhealthdata.validation.result.TestResultType;
import org.openhealthdata.validation.result.ErrorType;

import org.astm.ccr.SocialHistoryType;
import org.astm.ccr.CodedDescriptionType;


#declare any global variables here
global ValidationResultManager val_result;


rule "Social History status must be one of the required string values"
@title ("Social History status must be one of the required string values")
@testid ("88b26e2e-3ddc-4791-823a-d141b04f5eaf")
@description ("Social History status must be one of the required string values: Active, Prior History No Longer Active, Unknown.")
@source ("E2369-05 Table A1.1 Page 18")
@profile ("E2369-05")
@author ("openhealthdata")
	when
		$sht:SocialHistoryType($s:status)
		CodedDescriptionType( this == $s, $t:text not in ("Active", 
			"Prior History No Longer Active", "Unknown") )
	then
		String testid = drools.getRule().getMetaAttribute("testid");
		String title = drools.getRule().getMetaAttribute("title");
		String description = drools.getRule().getMetaAttribute("description");
		String source = drools.getRule().getMetaAttribute("source");
		String profile = drools.getRule().getMetaAttribute("profile"); 
		val_result.addTest(
			testid,
			title,
			description+ " Source: "+
			source,
			TestResultType.FAILED, profile);
		ErrorType e = new ErrorType();
		e.setMessage("SocialHistory item ["+$sht.getCCRDataObjectID()+"] has an invalid status value ["+$t+"]");
		e.setServerity(ErrorType.FATAL);
		val_result.addError(testid, e);
end
