/*
 * Copyright 2010 OpenHealthData, Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.

 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
 #created on: Apr 29, 2008
package org.astm.ccr.rules.core

#list any import classes here.
import java.util.List;
import org.astm.ccr.DoseCalculationType;
import org.astm.ccr.MeasureType;
import org.astm.ccr.CodeType;


#declare any global variables here




rule "ccr DoseCalculation - calculationequation"
	
	when
		$d : DoseCalculationType( calculationEquation != null )
	then 
		for(CodeType ct : $d.getCalculationEquation().getCode()){
			insert(ct);
		}
end

rule "ccr DoseCalculation - dose"
	when
		DoseCalculationType( $d:dose != null )
	then
		insert($d);
end

rule "ccr DoseCalculation - variable"
	when
		$d: DoseCalculationType($v:variable)
		List(this == $v, size >0)
	then
		for(DoseCalculationType.Variable v : $d.getVariable()){
			insert(v);
			if(v.getVariableModifier() != null){
				insert(v.getVariableModifier());
			}
		}
end