/*
 * Copyright 2010 OpenHealthData, Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.

 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
 #created on: Apr 29, 2008
package org.astm.ccr.rules.core

#list any import classes here.
import java.util.List;
import org.astm.ccr.NormalType;
import org.astm.ccr.CodeType;
import org.astm.ccr.InternalCCRLink;
import org.astm.ccr.SourceType;


#declare any global variables here


rule "ccr NormalType - code"
	when
		$n:NormalType($c:code)
		List(this == $c, size >0)
	then
		for(CodeType c: $n.getCode()){
			insert(c);
		}
end

rule "ccr NormalType - description"
	when
		NormalType($d: description != null)
	then
		insert($d);
end

rule "ccr NormalType - internalccrlink"
	when
		$n:NormalType($i:internalCCRLink)
		List(this == $i, size >0)
	then
		for (InternalCCRLink l : $n.getInternalCCRLink()){
			insert(l);
		}
end

rule "ccr NormalType - source"
	when
		$n:NormalType($s:source)
		List(this == $s, size >0)
	then
		for(SourceType s : $n.getSource()){
			insert(s);
		}
end

rule "ccr NormalType - type"
	when
		NormalType($t:type != null)
	then
		insert($t);
end

rule "ccr NormalType - units"
	when
		$n:NormalType(units != null)
	then
		for (CodeType c : $n.getUnits().getCode()){
			insert(c);
		}
end

rule "ccr NormalType - variablenomalmodifier"
	when
		NormalType($v:variableNomalModifier != null)
	then
		insert($v);
end