/*
 * Copyright 2010 OpenHealthData, Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.

 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
#created on: Apr 29, 2008
package org.astm.ccr.rules.core

#list any import classes here.
import org.astm.ccr.ActorType;
import org.astm.ccr.PersonNameType;
import org.astm.ccr.CommunicationType;
import org.astm.ccr.IDType;
import org.astm.ccr.InternalCCRLink;
import org.astm.ccr.CodedDescriptionType;
import org.astm.ccr.SourceType;
import java.util.List;

#declare any global variables here


rule "ccr ActorType - Person"
	
	when
		ActorType($p:person != null)
	then 
		if ($p.getGender() != null){
			insert($p.getGender());
		}
		if ($p.getDateOfBirth() != null){
			insert($p.getDateOfBirth());
		}
		if ($p.getName() != null){
			ActorType.Person.Name n = $p.getName();
			if (n.getBirthName() != null){
				insert(n.getBirthName());
			}
			if (n.getCurrentName() != null){
				insert(n.getCurrentName());
			}
			for (PersonNameType pnt : n.getAdditionalName()){
				insert(pnt);
			}
		}
end

rule "ccr ActorType - Address"
	when
		$at : ActorType($a:address)
		List(this == $a, size > 0)
	then
		for (ActorType.Address a : $at.getAddress()){
			if (a.getType() != null){
				insert(a.getType());
			}
			if (a.getStatus() != null){
				insert(a.getStatus());
			}
		}
end

rule "ccr ActorType - email"
	when
		$at : ActorType($e : EMail)
		List(this == $e, size > 0)
	then
		for (CommunicationType ct : $at.getEMail()){
			insert(ct);
		}
end

rule "ccr ActorType - ids"
	when
		$at: ActorType($i:IDs)
		List(this == $i, size >0) 
	then
		for (IDType id : $at.getIDs()){
			insert(id);
		}
end

rule "ccr ActorType - url"
	when
		$at: ActorType($u:URL)
		List(this == $u, size >0)
	then
		for (CommunicationType ct : $at.getURL()){
			insert(ct);
		}
end

rule "ccr ActorType - telephone"
	when
		$at: ActorType($t:telephone)
		List(this == $t, size >0)
	then
		for (CommunicationType ct : $at.getTelephone()){
			insert(ct);
		}
end

rule "ccr ActorType - internalccrlink"
	when
		$at: ActorType($i : internalCCRLink)
		List(this == $i, size >0)
	then
		for (InternalCCRLink lk : $at.getInternalCCRLink()){
			insert(lk);
		}
end

rule "ccr ActorType - relation"
	when
		$at: ActorType($r: relation) 
		List(this == $r, size >0)
	then
		for(CodedDescriptionType cdt : $at.getRelation()){
			insert(cdt);
		}
end

/*
rule "ccr ActorType - signature"
	when
		$at: ActorType($s : signature)
		List(this == $s, size >0)
	then
		for(Signature s : $at.getSignature()){
			insert(s);
		}
end
*/

rule "ccr ActorType - source"
	when
		$at: ActorType($s : source)
		List(this == $s, size >0)
	then
		for(SourceType st : $at.getSource()){
			insert(st);
		}
end

rule "ccr ActorType - specialty"
	when
		$at: ActorType($s: specialty)
		List(this==$s,size>0)
	then
		for (CodedDescriptionType cdt : $at.getSpecialty()){
			insert(cdt);
		}
end

rule "ccr ActorType - status"
	when
		ActorType($s:status != null)
	then
		insert($s);
end