/*
 * Copyright 2010 OpenHealthData, Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.

 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
#created on: Apr 29, 2008
package org.astm.ccr.rules.core

#list any import classes here.
import org.astm.ccr.AlertType;
import org.astm.ccr.Reaction;
import org.astm.ccr.Agent;
import java.util.List;


#declare any global variables here



rule "ccr Alert - agent"
	when
		$at : AlertType($a:agent)
		List(this == $a, size >0)
	then
		for(Agent a : $at.getAgent()){
			insert(a);
		}
end

rule "ccr Alert - reaction"
	when
		$at : AlertType($r:reaction)
		List(this == $r, size >0)
	then
		for(Reaction r : $at.getReaction()){
			insert(r);
		}
end