/*
 * Copyright 2010 OpenHealthData, Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.

 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
#created on: Apr 29, 2008
package org.astm.ccr.rules.core

#list any import classes here.
import java.util.List;
import org.astm.ccr.CurrentHealthStatusType;
import org.astm.ccr.DateTimeType;
import org.astm.ccr.InternalCCRLink;
import org.astm.ccr.SourceType

#declare any global variables here




rule "ccr CurrentHealthStatusType - datetime"
	
	when
		$c: CurrentHealthStatusType($d:dateTime)
		List(this == $d, size >0) 
	then 
		for(DateTimeType dt : $c.getDateTime()){
			insert(dt);
		}
end

rule "ccr CurrentHealthStatusType - description"
	
	when
		CurrentHealthStatusType( $d:description )
	then 
		insert($d);
end

rule "ccr CurrentHealthStatusType - internalCCRLink"
	
	when
		$c: CurrentHealthStatusType( $i: internalCCRLink )
		List(this == $i, size >0)
	then 
		for (InternalCCRLink lk : $c.getInternalCCRLink()){
			insert(lk);
		}
end

rule "ccr CurrentHealthStatusType - source"
	
	when
		$c: CurrentHealthStatusType( $s:source )
		List(this == $s, size >0)
	then 
		for(SourceType s : $c.getSource()){
			insert(s);
		}
end