/*
 * Copyright 2010 OpenHealthData, Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.

 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
 #created on: Mar 21, 2008
package org.astm.ccr.rules.core

#list any import classes here.
import org.astm.ccr.*;
import org.astm.ccr.StructuredProductType.Product;
import java.util.List;
import java.lang.Number;


#declare any global variables here

/*
rule "ccr Found Object"
	when
		$o:Object()
	then
		System.out.println("Object Found: "+$o.getClass().getName());
end

rule "Object Count"
	salience -100 
	when
		$total : Number() from accumulate (Object(),sum(1))
	then
		System.out.println("Total Objects Found: "+$total);
end

rule "second rule"
	when
		$c : ActorReferenceType()
	then
		System.out.println("Found ActorRef: "+$c.getActorID());
end

rule "second point two rule"
	when
		$a : ActorType()
	then
		System.out.println("Found ActorObjectID: "+$a.getActorObjectID());
end
*/
/*
rule "third rule"
	when
		$d: DateTimeType($e: exactDateTime != null)
	then
		System.out.println("Found Exact Time: "+$e);
end

rule "ccr found Problem"
	when
		$problem : ProblemType($d:description)
		CodedDescriptionType( this == $d, text !=null )
	then
		System.out.println( "Found CCR problem: " + $problem.getDescription().getText() ); 
end

rule "ccr found StructuredProductType"
	when
		$spt : StructuredProductType($p: product)
	then
		System.out.println("Found StructuredProductType: "+$spt.getProduct().get(0).getProductName().getText());
end
*/