/*
 * Copyright 2010 OpenHealthData, Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.

 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
#created on: Apr 29, 2008
package org.astm.ccr.rules.core

#list any import classes here.
import java.util.List;
import org.astm.ccr.EpisodesType;
import org.astm.ccr.EpisodeType;
import org.astm.ccr.SourceType;
import org.astm.ccr.InternalCCRLink;

#declare any global variables here


rule "ccr EpisodesType - frequency"
	when
		EpisodesType($f:frequency != null)
	then
		insert($f);
end

rule "ccr EpisodesType - episode"
	when
		$et: EpisodesType($e:episode)
		List(this == $e, size >0)
	then
		for(EpisodeType e: $et.getEpisode()){
			insert(e);
		}
end

rule "ccr EpisodesType - internalCCRLink"
	when
		$et: EpisodesType($i:internalCCRLink)
		List(this == $i, size >0)
	then
		for (InternalCCRLink i : $et.getInternalCCRLink()){
			insert(i);
		}
end

rule "ccr EpisodesType - source"
	when
		$et: EpisodesType($s:source)
		List(this == $s, size >0)
	then
		for(SourceType s : $et.getSource()){
			insert(s);
		}
end
/*
rule "ccr EpisodesType - signature"
	when
		$et: EpisodesType($s:signature)
		List(this == $s, size >0)
	then
		
end
*/