/*
 * Copyright 2010 OpenHealthData, Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.

 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
 #created on: Apr 29, 2008
package org.astm.ccr.rules.core

#list any import classes here.
import java.util.List;
import org.astm.ccr.IDType;
import org.astm.ccr.DateTimeType;
import org.astm.ccr.SourceType;
import org.astm.ccr.InternalCCRLink;


#declare any global variables here


rule "ccr IDType - datetime"
	when
		$i: IDType($d:dateTime)
		List(this == $d, size >0)
	then
		for(DateTimeType d : $i.getDateTime()){
			insert(d);
		}
end

rule "ccr IDType - internalccrlink"
	when
		$i: IDType($l:internalCCRLink)
		List(this == $l, size >0)
	then
		for(InternalCCRLink i : $i.getInternalCCRLink()){
			insert(i);
		}
end

rule "ccr IDType - issuedby"
	when
		IDType($i:issuedBy != null)
	then
		insert($i);
end

rule "ccr IDType - source"
	when
		$i: IDType($s: source)
		List(this == $s, size >0) 
	then
		for(SourceType s : $i.getSource()){
			insert(s);
		}
end

rule "ccr IDType - type"
	when
		IDType($t:type != null)
	then
		insert($t);
end