/*
 * Copyright 2010 OpenHealthData, Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.

 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
 #created on: Apr 29, 2008
package org.astm.ccr.rules.core

#list any import classes here.
import java.util.List;
import org.astm.ccr.SourceType;
import org.astm.ccr.ActorReferenceType;


#declare any global variables here


rule "ccr SourceType - actor"
	when
		$s:SourceType($a:actor)
		List(this == $a, size >0)
	then
		for(ActorReferenceType a : $s.getActor()){
			insert(a);
		}
end

rule "ccr SourceType - datetime"
	when
		SourceType($d:dateTime != null)
	then
		insert($d);
end

rule "ccr SourceType - description"
	when
		SourceType($d:description != null)
	then
		insert($d);
end