/*
 * Copyright 2010 OpenHealthData, Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.

 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
#created on: Apr 29, 2008
package org.astm.ccr.rules.core

#list any import classes here.
import org.astm.ccr.Agent;
import org.astm.ccr.CCRCodedDataObjectType;
import org.astm.ccr.ProblemType;
import org.astm.ccr.ProcedureType;
import org.astm.ccr.StructuredProductType;
import org.astm.ccr.ResultType;
import java.util.List;


#declare any global variables here





rule "ccr Agent - EnvironmentAgent"
	when
		$a:Agent($ea:environmentalAgents)
		List(this == $ea, size >0)
	then
		for(CCRCodedDataObjectType cdt : $ea.getEnvironmentalAgent()){
			insert (cdt);
		}
end

rule "ccr Agent - Problem"
	when
		$a : Agent($p:problems)
		List(this == $p, size >0)
	then
		for(ProblemType pt : $p.getProblem()){
			insert (pt);
		}
end

rule "ccr Agent - Procedure"
	when
		$a : Agent($p:procedures)
		List(this == $p, size >0)
	then
		for(ProcedureType pt : $p.getProcedure()){
			insert (pt);
		}
end

rule "ccr Agent - Results"
	when
		$a : Agent($r: results)
		List(this == $r, size >0)
	then
		for(ResultType rt : $r.getResult()){
			insert (rt);
		}
end

rule "ccr Agent - Products"
	when
		$a : Agent($p:products)
		List(this == $p, size >0)
	then
		for(StructuredProductType pt : $p.getProduct()){
			insert (pt);
		}
end
