/*
 * Copyright 2010 OpenHealthData, Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.

 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
#created on: Apr 29, 2008
package org.astm.ccr.rules.core

#list any import classes here.
import java.util.List;
import org.astm.ccr.AuthorizationType;
import org.astm.ccr.PurposeType;
import org.astm.ccr.StructuredProductType;


#declare any global variables here




rule "ccr AuthorizationType - purpose"
	
	when
		$au : AuthorizationType($p:purpose)
		List(this == $p, size >0)
	then 
		for (PurposeType pt : $au.getPurpose()){
			insert(pt);
		}
end

rule "ccr AuthorizationType - practitioners"
	when
		$au : AuthorizationType($p:practitioners != null)
	then
		insert($p);
end

rule "ccr AuthorizationType - encounters"
	when
		$au : AuthorizationType($e:encounters != null)
	then
		insert($e);
end

rule "ccr AuthorizationType - immunizations"
	when
		$au: AuthorizationType($i:immunizations != null)
	then
		for (StructuredProductType spt : $i.getImmunization()){
			insert(spt);
		}
end

rule "ccr AuthorizationType - medications"
	when
		$au: AuthorizationType($m:medications != null)
	then
		insert($m);
end

rule "ccr AuthorizationType - procedures"
	when
		$au: AuthorizationType($p:procedures != null)
	then
		insert($p);
end

rule "ccr AuthorizationType - products"
	when
		$au: AuthorizationType($p:products != null)
	then
		insert($p);
end

rule "ccr AuthorizationType - "
	when
		$au: AuthorizationType($s: services != null)
	then
		insert($s);
end