/*
 * Copyright 2010 OpenHealthData, Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.

 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
 #created on: Apr 29, 2008
package org.astm.ccr.rules.core

#list any import classes here.
import java.util.List;
import org.astm.ccr.DurationType;
import org.astm.ccr.CodedDescriptionType;
import org.astm.ccr.CodeType;
import org.astm.ccr.DateTimeType;


#declare any global variables here


rule "ccr DurationType - code"
	when
		$d: DurationType($c:code)
		List(this == $c, size >0)
	then
		for(CodeType c : $d.getCode()){
			insert(c);
		}
end

rule "ccr DurationType - datetime"
	when
		$d: DurationType($dt:dateTime)
		List(this == $dt, size >0)
	then
		for (DateTimeType dt : $d.getDateTime()){
			insert(dt);
		}
end

rule "ccr DurationType - description"
	when
		DurationType($d:description != null)
	then
		insert($d);
end

rule "ccr DurationType - units"
	when
		$d: DurationType(units != null)
	then
		for(CodeType ct : $d.getUnits().getCode()){
			insert(ct);
		}
end

rule "ccr DurationType - variabledurationmodifier"
	when
		$d: DurationType($v:variableDurationModifier != null)
	then
		insert($v);
end