/*
 * Copyright 2010 OpenHealthData, Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.

 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
 #created on: Apr 29, 2008
package org.astm.ccr.rules.core

#list any import classes here.
import java.util.List;
import org.astm.ccr.PurposeType;
import org.astm.ccr.DateTimeType;
import org.astm.ccr.Indications;
import org.astm.ccr.PlanOfCareType;
import org.astm.ccr.CodedDescriptionType;

#declare any global variables here


rule "ccr PurposeType - datetime"
	when
		$p: PurposeType($d:dateTime)
		List(this == $d, size >0)
	then
		for(DateTimeType d : $p.getDateTime()){
			insert(d);
		}
end

rule "ccr PurposeType - description"
	when
		$p: PurposeType($d:description)
		List(this == $d, size >0)
	then
		for(CodedDescriptionType c : $p.getDescription()){
			insert(c);
		}
end

rule "ccr PurposeType - indications"
	when
		$p: PurposeType($i:indications)
		List(this == $i, size >0)
	then
		for (Indications i : $p.getIndications()){
			insert(i);
		}
end

rule "ccr PurposeType - orderrequest"
	when
		$p: PurposeType($o:orderRequest)
		List(this == $o, size >0)
	then
		for (PlanOfCareType p : $p.getOrderRequest()){
			insert(p);
		}
end
